// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKkPgtbNVSbh3fF1Rw79U5okUElvtaYJU',
    appId: '1:598915125682:web:f9b3bb5cb442194dfad4ab',
    messagingSenderId: '598915125682',
    projectId: 'flutter-chat-app-cd30b',
    authDomain: 'flutter-chat-app-cd30b.firebaseapp.com',
    storageBucket: 'flutter-chat-app-cd30b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAtvoiD4hDbKVnX3KBGFHui6zAGquBTzE',
    appId: '1:598915125682:android:17046f732cbd4183fad4ab',
    messagingSenderId: '598915125682',
    projectId: 'flutter-chat-app-cd30b',
    storageBucket: 'flutter-chat-app-cd30b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlBtTgVRstgwcQZcp20gmfXAIroagFmto',
    appId: '1:598915125682:ios:8b593294cb80b427fad4ab',
    messagingSenderId: '598915125682',
    projectId: 'flutter-chat-app-cd30b',
    storageBucket: 'flutter-chat-app-cd30b.appspot.com',
    iosBundleId: 'com.shrimadbhagwat.chatapp.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlBtTgVRstgwcQZcp20gmfXAIroagFmto',
    appId: '1:598915125682:ios:6a0f0041a83b3434fad4ab',
    messagingSenderId: '598915125682',
    projectId: 'flutter-chat-app-cd30b',
    storageBucket: 'flutter-chat-app-cd30b.appspot.com',
    iosBundleId: 'com.shrimadbhagwat.chatapp.chatApp.RunnerTests',
  );
}
